- name: Change to project directory
  run: cd my_flutter_project

- name: Install Dependencies
  run: flutter pub get
  working-directory: my_flutter_project

- name: Build iOS (no code signing)
  run: flutter build ios --no-codesign
  working-directory: my_flutter_project
